# runs-on:                  https://github.com/actions/virtual-environments
# setup-python:             https://github.com/actions/setup-python
# actions-setup-perl:       https://github.com/marketplace/actions/setup-perl-environment
# Strawberry Perl 5.12.3.0: https://strawberryperl.com/download/5.12.3.0/strawberry-perl-5.12.3.0-portable.zip
# Strawberry Perl 5.32.1.1: https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit-portable.zip
# actions-upload-artifact:  https://github.com/actions/upload-artifact

name: Build Win
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build_XSTools:

    name: XSTools ${{ matrix.os }} (python ${{ matrix.python }}) (perl ${{ matrix.perl }}) ${{ matrix.architecture }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-2016
          python: 2.7
          architecture: x86
          perl: 5.12
          strawberry_distr: 'https://strawberryperl.com/download/5.12.3.0/strawberry-perl-5.12.3.0-portable.zip'

        - os: windows-latest
          python: 3
          architecture: x86
          perl: '5.32'
          strawberry_distr: 'https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit-portable.zip'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # setup Windows matrix: python 2.7_x86 + strawberry perl 5.12_x86 and python 3_x86 and strawberry perl 5.32_x86
    - name: setup-python ${{ matrix.python }} ${{ matrix.architecture }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.architecture }}

    - name: Replace perl to ${{ matrix.perl }} ${{ matrix.architecture }}
      run: |
        echo "================================================================="
        echo "== previous version of Perl:"
        echo "================================================================="
        perl --version
        echo "================================================================="
        echo "== remove the default perl"
        echo "================================================================="
        rm -r C:/Strawberry/*
        echo "================================================================="
        echo "== download strawberry perl ${{ matrix.perl }} ${{ matrix.architecture }}"
        echo "================================================================="
        Invoke-WebRequest ${{ matrix.strawberry_distr }} -OutFile strawberry.zip
        7z.exe x strawberry.zip -o"C:/Strawberry"
        echo "================================================================="
        echo "== a new version of Perl:"
        echo "================================================================="
        perl --version
        echo "================================================================="
        echo "== remove g++ x64"
        echo "================================================================="
        # package removal takes too long (4 minutes). Instead, we can delete 1 file
        # choco uninstall mingw
        rm C:\ProgramData\Chocolatey\bin\g++.exe

    - name: Environment check
      run: |
        echo "================================================================="
        echo "== python version:"
        echo "================================================================="
        python -V
        echo "================================================================="
        echo "== perl version:"
        echo "================================================================="
        perl --version
        echo "================================================================="
        echo "== Time::HiRes module:"
        echo "================================================================="
        perl -e "use Time::HiRes;"
        if  ($?)  {echo OK}
        echo "================================================================="
        echo "== Compress::Zlib module:"
        echo "================================================================="
        perl -e "use Compress::Zlib;"
        if  ($?)  {echo OK}
        echo "================================================================="
        echo "== check g++ version:"
        echo "================================================================="
        g++ --version
        echo "================================================================="
        echo "== check gmake version:"
        echo "================================================================="
        gmake --version

    - name: Run make XSTools.dll
      run: |
        gmake all
        echo "================================================================="
        ls src\auto\XSTools\XSTools.dll
        ls src\auto\XSTools\NetRedirect.dll

    - name: Making artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}_perl${{ matrix.perl }}${{ matrix.architecture }}
        path: |
          src\auto\XSTools\XSTools.dll
          src\auto\XSTools\NetRedirect.dll