# runs-on:            https://github.com/actions/virtual-environments
# setup-python:       https://github.com/actions/setup-python
# actions-setup-perl: https://github.com/marketplace/actions/setup-perl-environment

name: Build Win
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build_XSTools:

    name: XSTools ${{ matrix.os }} (python ${{ matrix.python }}) (perl ${{ matrix.perl }}) x${{ matrix.test }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-2016
          python: 3
          architecture: x86
          perl: '5.30'
          test: 64

        - os: windows-2016
          python: 3
          architecture: x86
          perl: '5.30'
          test: 32

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # setup Windows matrix: python 3_x86 and strawberry perl 5.30_x64, 5.30_x86
    - name: setup-python ${{ matrix.python }} ${{ matrix.architecture }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.architecture }}

    - name: Replace perl to 5.30.3.1 x${{ matrix.test }}
      run: |
        echo "================================================================="
        echo "== previous version"
        echo "================================================================="
        perl --version
        echo "================================================================="
        echo "== remove the default perl"
        echo "================================================================="
        rm -r C:/Strawberry/*
        echo "================================================================="
        echo "== remove the default perl"
        echo "================================================================="
        #Invoke-WebRequest https://strawberryperl.com/download/5.30.3.1/strawberry-perl-5.30.3.1-64bit-portable.zip -OutFile strawberry.zip
        Invoke-WebRequest https://strawberryperl.com/download/5.30.3.1/strawberry-perl-5.30.3.1-${{ matrix.test }}bit-portable.zip -OutFile strawberry.zip
        7z.exe x strawberry.zip -o"C:/Strawberry"
        echo "================================================================="
        echo "== a new version"
        echo "================================================================="
        perl --version

    - name: Environment check
      run: |
        echo "------------- check g++ version -------------"
        g++ --version
        echo "------------- perl version -------------"
        perl --version
        echo "------------- Time::HiRes module -------------"
        perl -e "use Time::HiRes;"
        echo "------------- Compress::Zlib module -------------"
        perl -e "use Compress::Zlib;"
        echo "------------- python version -------------"
        python -V

    - name: Run make XSTools.dll
      run: |
        make all
        echo "================================================================="
        echo "DONE:"
        #dir src\auto\XSTools\ | findstr "dll"
        ls src\auto\XSTools\NetRedirect.dll
        ls src\auto\XSTools\XSTools.dll