# runs-on:                  https://github.com/actions/virtual-environments
# setup-python:             https://github.com/actions/setup-python
# actions-setup-perl:       https://github.com/marketplace/actions/setup-perl-environment
# Strawberry Perl 5.22.3.1: https://strawberryperl.com/download/5.22.3.1/strawberry-perl-5.22.3.1-32bit-portable.zip
# actions-upload-artifact:  https://github.com/actions/upload-artifact

name: Build Win
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build_XSTools:

    name: XSTools ${{ matrix.os }} (python ${{ matrix.python }}) (perl ${{ matrix.perl }}) x${{ matrix.perl_arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-2016
          python: 3
          architecture: x86
          perl: '5.22'
          perl_arch: 64

        - os: windows-2016
          python: 3
          architecture: x86
          perl: '5.22'
          perl_arch: 32

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # setup Windows matrix: python 3_x86 and strawberry perl 5.32_x64, 5.32_x86
    - name: setup-python ${{ matrix.python }} ${{ matrix.architecture }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.architecture }}

    - name: Replace perl to 5.32.3.1 x${{ matrix.perl_arch }}
      run: |
        echo "================================================================="
        echo "== previous version of Perl:"
        echo "================================================================="
        perl --version
        echo "================================================================="
        echo "== remove the default perl"
        echo "================================================================="
        rm -r C:/Strawberry/*
        echo "================================================================="
        echo "== download strawberry perl ${{ matrix.perl }} ${{ matrix.perl_arch }}"
        echo "================================================================="
        Invoke-WebRequest https://strawberryperl.com/download/5.22.3.1/strawberry-perl-5.22.3.1-${{ matrix.perl_arch }}bit-portable.zip -OutFile strawberry.zip
        7z.exe x strawberry.zip -o"C:/Strawberry"
        echo "================================================================="
        echo "== a new version of Perl:"
        echo "================================================================="
        perl --version
        echo "================================================================="
        echo "== uninstall mingw x64"
        echo "================================================================="
        choco uninstall mingw

    - name: Environment check
      run: |
        echo "================================================================="
        echo "== check g++ version:"
        echo "================================================================="
        g++ --version
        echo "================================================================="
        echo "== perl version:"
        echo "================================================================="
        perl --version
        echo "================================================================="
        echo "== Time::HiRes module:"
        echo "================================================================="
        perl -e "use Time::HiRes;"
        echo "================================================================="
        echo "== Compress::Zlib module:"
        echo "================================================================="
        perl -e "use Compress::Zlib;"
        echo "================================================================="
        echo "== python version:"
        echo "================================================================="
        python -V

    - name: Run make XSTools.dll
      run: |
        gmake all
        echo "================================================================="
        ls src\auto\XSTools\XSTools.dll
        ls src\auto\XSTools\NetRedirect.dll

    - name: Making artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}_perl${{ matrix.perl }}x${{ matrix.perl_arch }}
        path: |
          src\auto\XSTools\XSTools.dll
          src\auto\XSTools\NetRedirect.dll